<table class="table table-bordered">
    <thead>
    <tr>
        <th><?= $this->translate('Title'); ?></th>
        <th><?= $this->translate('Content'); ?></th>
        <th><?= $this->translate('Creation Date'); ?></th>
        <th><?= $this->translate('Modification Date'); ?></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->posts as $post) : ?>
        <tr>
            <td><?php echo $post->getTitulo(); ?></td>
            <td><?php echo $post->getConteudo(); ?></td>
            <td>
                <?= $this->dateFormat(
                    $post->getDataCriacao(),
                    IntlDateFormatter::SHORT,
                    IntlDateFormatter::SHORT,
                    'pt_BR'
                ); ?>
            </td>
            <td>
                <?php if ($post->getDataAtualizacao()) : ?>
                    <?= $this->dateFormat(
                        $post->getDataAtualizacao(),
                        IntlDateFormatter::SHORT,
                        IntlDateFormatter::SHORT,
                        'pt_BR'
                    ); ?>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
