<table class="table table-bordered">
    <thead>
    <tr>
        <th>Titulo</th>
        <th>Conteudo</th>
        <th>Data Criação</th>
        <th>Data Atualização</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->posts as $post) : ?>
        <tr>
            <td><?php echo $post->getTitulo(); ?></td>
            <td><?php echo $post->getConteudo(); ?></td>
            <td><?php echo $post->getDataCriacao()->format('d/m/Y H:i'); ?></td>
            <td>
                <?php
                    if ($post->getDataAtualizacao()) {
                        echo $post->getDataAtualizacao()->format('d/m/Y H:i');
                    }
                ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
